# Notebook Lineare Regressie
- Modules binnenhalen

In [2]:
import numpy as np

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# sklearn.linear_model.LinearRegression¶
# https://www.youtube.com/watch?v=J_LnPL3Qg70

## Eerste dataset binnenhalen (Compleet, met outliers, zonder bmi)
... En helaas ook nog met twee negatieve lifespans

In [25]:
lsd = pd.read_csv('lsdata230309.csv')
display(lsd.head())
display(lsd.shape)

genetic  length   mass  exercise  smoking  alcohol  sugar  lifespan
0     73.9   185.0   99.7       0.9      0.0      2.4    6.9      73.1
1     86.0   172.0  105.4       1.8      8.1      0.4    4.2      85.0
2     83.3   176.0  111.4       1.1      0.8      4.6    7.5      81.6
3     82.8   164.0  111.4       4.7     11.8      1.0    2.9      81.0
4     78.7   178.0   71.6       1.5      8.3      4.9    5.5      75.0

(4086, 8)

X en y definieren en dataset verdelen in trainingsgedeelte en testgedeelte:

In [54]:
y = lsd.lifespan.values#.reshape(-1, 1)  # als ik hier 'reshape gebruik, krijg ik bij reg.fit() geen foutmelding. 
#Gebruik ik reshape twee blokken verderop, dan blijf ik de foutmelding houden ?!
# # https://www.alpharithms.com/reshaping-data-for-linear-regression-with-pandas-numpy-and-scikit-learn-033714/
X = lsd[['genetic','length','mass','exercise','smoking','alcohol','sugar']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [5]:
# print("Dimensions of X before reshaping: {}".format(X.shape))
# print("Dimensions of y before reshaping: {}".format(y.shape))


In [6]:
print("Dimensions of X after reshaping: {}".format(X.shape))
print("Dimensions of y after reshaping: {}".format(y.shape))


Dimensions of X after reshaping: (4086, 7)
Dimensions of y after reshaping: (4086,)


Linear Regressie model opzetten en train set runnen:

In [18]:
reg = linear_model.LinearRegression() # create a linear regression class object
reg.fit(X_train, y_train)

LinearRegression()

In [55]:
reg.coef_ # geeft de coeff van elk van de 7 features

array([ 1.00107787,  0.01951121, -0.02098709,  0.78121191, -0.26930836,
       -0.20203216, -0.05311479])

In [20]:
reg.intercept_ # punt waar de intercept de y-as kruist


-2.2986241278888286

In [21]:
lsd.describe()

genetic       length         mass     exercise      smoking  \
count  4086.000000  4086.000000  4086.000000  4086.000000  4086.000000   
mean     82.280127   183.879344    92.273837     2.403353     9.812677   
std       7.440070    12.627470    25.800771     1.170593     6.919057   
min      63.900000   154.000000    50.000000     0.100000     0.000000   
25%      77.600000   175.000000    71.425000     1.500000     3.400000   
50%      81.800000   184.000000    89.500000     2.200000     9.500000   
75%      86.700000   193.000000   110.875000     3.200000    15.900000   
max     102.200000   214.000000   163.600000     5.500000    22.200000   

           alcohol        sugar     lifespan  
count  4086.000000  4086.000000  4086.000000  
mean      2.266006     6.484973    80.137959  
std       1.801020     2.709868     8.041656  
min       0.000000     0.700000    -1.000000  
25%       0.600000     4.400000    75.000000  
50%       1.700000     6.300000    79.700000  
75%       4.000000     8.400000    85.200000  
max       6.000000    13.800000   105.100000

In [11]:
display(reg.predict([[75.0, 176.0, 113.4, 2.0, 15.0, 1.0, 4.0]])) # willekeurige waarden
display(reg.predict([[82.28, 183.88, 92.27, 2.4, 9.81, 2.27, 6.48]])) # alle gemiddelde waarden van de kolommen genomen.

array([70.94456064])

array([80.15150272])

### Testen hoe goed mijn model werkt
- theorie zoeken over mse en rmse

In [12]:
# score() geeft de determinatiecoëfficiënt (R2). R2 is een getal tussen de 0 en 1 dat de mate aanduidt waarin een statistisch model in staat is een bepaalde uitkomst te voorspellen.
score = reg.score(X_test,y_test) 
display(score)

0.8681071982839249

In [26]:
# y_predict_test = reg.predict(X_test)
# display(y_predict_test)

In [24]:
# RMSE is the standard deviation of the residuals (prediction errors). Residuals are a measure of how far from the regression line data points are; 
# RMSE is a measure of how spread out these residuals are. In other words, it tells you how concentrated the data is around the line of best fit. 
mse = mean_squared_error(y_test, predict_test)
rmse = (math.sqrt(mse))
print (mse)
print(rmse)

9.573014508797131
3.094028847441008


In [17]:
print("R^2: {}".format(reg.score(X_test, y_test)))
rmse = np.sqrt(mean_squared_error(y_test, y_predict_test))
print("Root Mean Squared Error: {}".format(rmse))

R^2: 0.8681071982839249
Root Mean Squared Error: 3.094028847441008


## Tweede dataset binnenhalen (Met outliers, zonder 'length' en 'mass', met bmi)

In [27]:
lsd = pd.read_csv('lsdLight230310.csv')
display(lsd.head())
display(lsd.shape)

genetic  exercise  smoking  alcohol  sugar  lifespan   bmi
0     73.9       0.9      0.0      2.4    6.9      73.1  29.0
1     86.0       1.8      8.1      0.4    4.2      85.0  36.0
2     83.3       1.1      0.8      4.6    7.5      81.6  36.0
3     82.8       4.7     11.8      1.0    2.9      81.0  41.0
4     78.7       1.5      8.3      4.9    5.5      75.0  23.0

(4084, 7)

X en y definieren en dataset verdelen in trainingsgedeelte en testgedeelte:

In [29]:
y = lsd.lifespan.values
X = lsd[['genetic','exercise','smoking','alcohol','sugar','bmi']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Testen:


In [36]:
from sklearn.tree import DecisionTreeRegressor
lsd = pd.read_csv('lsdata230309.csv')
display(lsd.head())
display(lsd.shape)

genetic  length   mass  exercise  smoking  alcohol  sugar  lifespan
0     73.9   185.0   99.7       0.9      0.0      2.4    6.9      73.1
1     86.0   172.0  105.4       1.8      8.1      0.4    4.2      85.0
2     83.3   176.0  111.4       1.1      0.8      4.6    7.5      81.6
3     82.8   164.0  111.4       4.7     11.8      1.0    2.9      81.0
4     78.7   178.0   71.6       1.5      8.3      4.9    5.5      75.0

(4086, 8)

In [44]:
lsda = lsd.astype(int)
display(lsda.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4086 entries, 0 to 4085
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genetic   4086 non-null   int64
 1   length    4086 non-null   int64
 2   mass      4086 non-null   int64
 3   exercise  4086 non-null   int64
 4   smoking   4086 non-null   int64
 5   alcohol   4086 non-null   int64
 6   sugar     4086 non-null   int64
 7   lifespan  4086 non-null   int64
dtypes: int64(8)
memory usage: 255.5 KB


None

In [58]:
# y = lsd.lifespan.values
# X = lsd[['genetic','length','mass','exercise','smoking','alcohol','sugar']].values
# X_train, X_test, y_train, y_test = train_test_split(features, lsda['lifespan'], random_state = 0)
X, y = load_lsd(return_X_y=True)
regressor = DecisionTreeRegressor(random_state=0)
cross_val_score(regressor, X, y, cv=10)

NameError: name 'load_lsd' is not defined

In [46]:
dt = DecisionTreeRegressor(max_depth=8,
min_samples_leaf=0.13,
random_state=3)

In [47]:
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=8, min_samples_leaf=0.13, random_state=3)

In [48]:
y_pred = dt.predict(X_test)

In [49]:
mse_dt = mse(y_test, y_pred)

TypeError: 'numpy.float64' object is not callable