# Notebook Lineare Regressie

Modules binnenhalen

In [112]:
import numpy as np

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

## Eerste dataset binnenhalen (Compleet, met outliers, zonder bmi)

In [113]:
lsd = pd.read_csv('lsdata230309.csv')
display(lsd.head())

genetic  length   mass  exercise  smoking  alcohol  sugar  lifespan
0     73.9   185.0   99.7       0.9      0.0      2.4    6.9      73.1
1     86.0   172.0  105.4       1.8      8.1      0.4    4.2      85.0
2     83.3   176.0  111.4       1.1      0.8      4.6    7.5      81.6
3     82.8   164.0  111.4       4.7     11.8      1.0    2.9      81.0
4     78.7   178.0   71.6       1.5      8.3      4.9    5.5      75.0

X en y definieren en dataset verdelen in trainingsgedeelte en testgedeelte:


In [114]:
y = lsd.lifespan.values
X = lsd[['genetic','length','mass','exercise','smoking','alcohol','sugar']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [115]:
reg = linear_model.LinearRegression() 
reg.fit(X_train, y_train)

LinearRegression()

In [116]:
reg.coef_ # geeft de coeff van elk van de 7 features

array([ 1.00107787,  0.01951121, -0.02098709,  0.78121191, -0.26930836,
       -0.20203216, -0.05311479])

In [117]:
reg.intercept_ # punt waar de intercept de y-as kruist

-2.2986241278888286

In [118]:
display(reg.predict([[75.0, 176.0, 113.4, 2.0, 15.0, 1.0, 4.0]])) # willekeurige waarden
display(reg.predict([[82.28, 183.88, 92.27, 2.4, 9.81, 2.27, 6.48]])) # alle gemiddelde waarden genomen.

array([70.94456064])

array([80.15150272])

## Testen hoe goed mijn model werkt
- score() geeft de determinatiecoëfficiënt (R2). R2 is een getal tussen de 0 en 1 dat de mate aanduidt waarin een statistisch model in staat is een bepaalde uitkomst te voorspellen.

In [119]:
score = reg.score(X_test,y_test)
display(score)

0.8681071982839249

In [120]:
predict_test = reg.predict(X_test)

- MSE is de standaardafwijking van de residuen (voorspellingsfouten). Residuen zijn een maat voor hoe ver de datapunten van de regressielijn verwijderd zijn. Hoe lager de MSE, des te beter het model een dataset 'fits'; 
- RMSE is een maat voor de spreiding van deze residuen. Met andere woorden, RMSE vertelt je hoe geconcentreerd de gegevens zijn rond de best passende lijn. Hoe lager de RMSE, hoe beter een bepaald model in staat is een dataset te "passen".

In [121]:
mse = mean_squared_error(y_test, predict_test)
rmse = (math.sqrt(mse))
display(mse)
display(rmse)

9.573014508797131

3.094028847441008

## Tweede dataset binnenhalen (met outliers, zonder 'length' en 'mass', met bmi)

In [123]:
lsd = pd.read_csv('lsdLight230310.csv')
display(lsd.describe())
display(lsd.shape)

genetic     exercise      smoking      alcohol        sugar  \
count  4084.000000  4084.000000  4084.000000  4084.000000  4084.000000   
mean     82.278624     2.403477     9.809035     2.266846     6.487169   
std       7.441333     1.170426     6.918614     1.801044     2.708622   
min      63.900000     0.100000     0.000000     0.000000     0.700000   
25%      77.600000     1.500000     3.375000     0.600000     4.400000   
50%      81.800000     2.200000     9.500000     1.700000     6.300000   
75%      86.700000     3.200000    15.900000     4.000000     8.400000   
max     102.200000     5.500000    22.200000     6.000000    13.800000   

          lifespan          bmi  
count  4084.000000  4084.000000  
mean     80.177693    27.681685  
std       7.840508     8.710015  
min      57.000000    11.000000  
25%      75.000000    21.000000  
50%      79.700000    26.000000  
75%      85.200000    33.000000  
max     105.100000    66.000000

(4084, 7)

X en y definieren en dataset verdelen in trainingsgedeelte en testgedeelte:

In [124]:
y = lsd.lifespan.values
X = lsd[['genetic','exercise','smoking','alcohol','sugar','bmi']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [125]:
reg = linear_model.LinearRegression() 
reg.fit(X_train, y_train)

LinearRegression()

In [126]:
reg.coef_ # geeft de coeff van elk van de 7 features

array([ 1.00081708,  0.80891882, -0.26521302, -0.2316613 , -0.06927231,
       -0.07203376])

In [127]:
reg.intercept_ # punt waar de intercept de y-as kruist

1.457310345219355

In [128]:
display(reg.predict([[82.28, 2.4, 9.81, 2.27, 6.48, 27.68]])) # alle gemiddelde waarden genomen.

array([80.17555481])

## Testen hoe goed mijn model op de tweede dataset werkt

In [129]:
score = reg.score(X_test,y_test)
display(score)

0.9806693050642554

In [130]:
predict_test = reg.predict(X_test)

In [131]:
mse = mean_squared_error(y_test, predict_test)
rmse = (math.sqrt(mse))
display(mse)
display(rmse)

1.1970815617658932

1.0941122253982418

## Derde dataset (zonder outliers, met 'length' en 'mass', met bmi)
- wonderlijk: het was de bedoeling om deze dataset zonder bmi te maken

In [132]:
lsd = pd.read_csv('lsdNoOutl230310.csv')
display(lsd.describe())

genetic       length         mass     exercise      smoking  \
count  3975.000000  3975.000000  3975.000000  3975.000000  3975.000000   
mean     82.036403   184.054088    91.682566     2.404277     9.781031   
std       7.086730    12.511810    25.225387     1.170234     6.912136   
min      64.000000   154.000000    50.000000     0.100000     0.000000   
25%      77.600000   175.000000    71.300000     1.500000     3.300000   
50%      81.700000   184.000000    89.000000     2.200000     9.500000   
75%      86.450000   193.000000   110.000000     3.200000    15.850000   
max     100.300000   214.000000   163.600000     5.500000    22.200000   

           alcohol        sugar     lifespan          bmi  
count  3975.000000  3975.000000  3975.000000  3975.000000  
mean      2.270340     6.484528    79.987044    27.407044  
std       1.803633     2.708536     7.454091     8.290604  
min       0.000000     0.700000    59.700000    11.000000  
25%       0.600000     4.400000    75.000000    21.000000  
50%       1.700000     6.300000    79.600000    26.000000  
75%       4.000000     8.400000    84.900000    33.000000  
max       6.000000    13.800000   100.400000    51.000000

X en y definieren en dataset verdelen in trainingsgedeelte en testgedeelte:


In [133]:
y = lsd.lifespan.values
X = lsd[['genetic','length','mass','exercise','smoking','alcohol','sugar','bmi']].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [134]:
reg = linear_model.LinearRegression() 
reg.fit(X_train, y_train) # standaard


LinearRegression()

In [135]:
reg.coef_ # geeft de coeff van elk van de 7 features

array([ 1.00062834, -0.03306715,  0.03313062,  0.81277307, -0.26385016,
       -0.22173559, -0.07086702, -0.17442886])

In [136]:
reg.intercept_ # punt waar de intercept de y-as kruist

7.321621514271996

In [137]:
display(reg.predict([[82.04, 184.05, 91.68, 2.4, 9.78, 2.27, 6.48, 27.41]])) # alle gemiddelde waarden genomen.

array([79.99112433])

## Test: hoe goed werkt het model op de derde dataset

In [138]:
score = reg.score(X_test,y_test)
display(score)

0.9803044592571766

In [139]:
predict_test = reg.predict(X_test)

In [140]:
mse = mean_squared_error(y_test, predict_test)
rmse = (math.sqrt(mse))
display(mse)
display(rmse)

1.0639184631048166

1.0314642325862864

## Test: zijn er nog verschillen als ik de bmi-kolom niet meeneem? Hoe goed werkt het model dan op de aangepaste derde dataset? 


In [141]:
lsd = pd.read_csv('lsdNoOutl230310.csv')
y = lsd.lifespan.values
Xe = lsd[['genetic','length','mass','exercise','smoking','alcohol','sugar']].values # zonder bmi; Xe = X_extra
Xe_train, Xe_test, y_train, y_test = train_test_split(Xe, y, test_size=0.2, random_state=42)

In [142]:
reg = linear_model.LinearRegression() 
reg.fit(Xe_train, y_train) 

LinearRegression()

In [143]:
score = reg.score(Xe_test,y_test)
display(score)

0.979444632196091

In [144]:
predict_test = reg.predict(Xe_test)

In [145]:
mse = mean_squared_error(y_test, predict_test)
rmse = (math.sqrt(mse))
display(mse)
display(rmse)

1.1103648083618949

1.0537384914493229

## Vierde dataset (zonder outliers, zonder 'length' en 'mass', met bmi)

In [146]:
lsd = pd.read_csv('lsdLightNoOutl230310.csv')
display(lsd.describe())

genetic     exercise      smoking      alcohol        sugar  \
count  3975.000000  3975.000000  3975.000000  3975.000000  3975.000000   
mean     82.036403     2.404277     9.781031     2.270340     6.484528   
std       7.086730     1.170234     6.912136     1.803633     2.708536   
min      64.000000     0.100000     0.000000     0.000000     0.700000   
25%      77.600000     1.500000     3.300000     0.600000     4.400000   
50%      81.700000     2.200000     9.500000     1.700000     6.300000   
75%      86.450000     3.200000    15.850000     4.000000     8.400000   
max     100.300000     5.500000    22.200000     6.000000    13.800000   

          lifespan          bmi  
count  3975.000000  3975.000000  
mean     79.987044    27.407044  
std       7.454091     8.290604  
min      59.700000    11.000000  
25%      75.000000    21.000000  
50%      79.600000    26.000000  
75%      84.900000    33.000000  
max     100.400000    51.000000

X en y definieren en dataset verdelen in trainingsgedeelte en testgedeelte:

In [156]:
y = lsd.lifespan.values
X = lsd[['genetic','exercise','smoking','alcohol','sugar','bmi']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [148]:
reg = linear_model.LinearRegression() 
reg.fit(X_train, y_train)

LinearRegression()

In [149]:
reg.coef_ # geeft de coeff van elk van de 7 features

array([ 1.00108466,  0.81202411, -0.2640704 , -0.22176916, -0.071128  ,
       -0.06447537])

In [150]:
reg.intercept_ # punt waar de intercept de y-as kruist

1.2283119328639316

In [151]:
display(reg.predict([[82.04,2.4, 9.78, 2.27, 6.48, 27.41]])) # alle gemiddelde waarden genomen.

array([79.99195106])

## Test: hoe goed werkt het model op de vierde dataset

In [152]:
score = reg.score(X_test,y_test)
display(score)

0.9799285570147052

In [153]:
predict_test = reg.predict(X_test)

In [154]:
mse = mean_squared_error(y_test, predict_test)
rmse = (math.sqrt(mse))
display(mse)
display(rmse)

1.0842240409668291

1.0412607939257241

## Conclusie Linear Regression
Vreemd genoeg is de RSME het beste bij de dataset waarbij zowel lengte, als gewicht als bmi opgenomen zijn. Ik had niet gedacht dat de bmi an sich nog iets toe te voegen had.